language: python
sudo: false
dist: trusty
python:
 - "2.7"
 - "3.5"
env:
  - "DJANGO_VERSION=1.11.2"
  - "DJANGO_VERSION=1.10.7"
install:
 - "pip install Django==$DJANGO_VERSION"
 - "python setup.py install"
script: "python tests/runtests.py"
